import "./globals.css";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { RootProvider } from "fumadocs-ui/provider";

// const inter = Inter({ subsets: ["latin"] });
// Using system fonts as fallback due to sandboxed environment
const inter = { className: "font-sans" };

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <RootProvider
          theme={{
            enabled: true,
          }}
          search={{
            enabled: true,
          }}
        >
          {children}
        </RootProvider>
      </body>
    </html>
  );
}
