import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { RootProvider } from "fumadocs-ui/provider";
import { baseOptions } from "./layout.config";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja" suppressHydrationWarning>
			<body className={`${inter.className} flex flex-col min-h-screen`}>
				<RootProvider {...baseOptions}>{children}</RootProvider>
			</body>
		</html>
	);
}
