name: commit

on:
  push:
    branches:
      - main

jobs:
  create-renovate-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Check for existing PR
        id: check_pr
        run: |
          count=$(gh pr list --state open --search "Renovate Updates in:title" | wc -l)
          echo "count=$count" >> "$GITHUB_OUTPUT"

      - name: Create new branch and PR
        if: ${{ steps.check_pr.outputs.count == '0' }}
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git fetch origin

          # 再作成
          git checkout -b renovate-pr origin/main

          # 空コミットで更新を促す
          git commit --allow-empty -m "Trigger Renovate Updates"
          git push -u origin renovate-pr

          # PR作成
          gh pr create -B main -H renovate-pr -t "Renovate Updates" -b ""
